### ISSUE TITLE
Could not resolved amzn dependencies

### ISSUE THREAD

**Issue by sr11231** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#1]
When running 'mvn package' I get 

> [ERROR] Failed to execute goal on project shims-common: Could not resolve dependencies for project com.amazonaws.glue:shims-common:jar:1.10.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.hive:hive-exec:jar:2.3.3-amzn-2, org.apache.hadoop:hadoop-common:jar:2.8.3-amzn-0, org.apache.hive:hive-metastore:jar:2.3.3-amzn-2: Could not find artifact org.apache.hive:hive-exec:jar:2.3.3-amzn-2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

.

I tried to add AWS EMR repositories as in  https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-artifact-repository.html but still it's failing in some jars.

**Comment by prabhacloud** [comment]
Can you try by updating your pom.xml by removing amzn-2 ?

org.apache.hive:hive-exec:jar:2.3.3
org.apache.hadoop:hadoop-common:jar:2.8.3
org.apache.hive:hive-metastore:jar:2.3.3 
org.apache.hive:hive-exec:jar:2.3.3

**Comment by sr11231** [comment]
Thanks.
I put the following:
```
    <hive2.version>2.3.3</hive2.version>
    <spark-hive.version>1.2.1.spark2</spark-hive.version>
    <hadoop.version>2.8.3</hadoop.version>
```

And I got an error:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.1:compile (default-compile) on project aws-glue-datacatalog-spark-client: Compilation failure: Compilation failure: 
> [ERROR] /Users/shrein/Development/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/aws-glue-datacatalog-spark-client/src/main/java/com/amazonaws/glue/catalog/metastore/AWSGlueDataCatalogHiveClientFactory.java:[7,41] error: cannot find symbol

**Comment by aws-austin-lee** [comment]
We have updated the README with instructions on patching Hive which is required for you to be able to build the Hive client.

**Comment by shreya668** [comment]
Tried the steps in README, to build the hive glue client. Still getting this exception:

[ERROR] Failed to execute goal on project aws-glue-datacatalog-hive2-client: Could not resolve dependencies for project com.amazonaws.glue:aws-glue-datacatalog-hive2-client:jar:1.10.0-SNAPSHOT: The following artifacts could not be resolved: com.amazonaws.glue:aws-glue-datacatalog-client-common:jar:1.10.0-SNAPSHOT, com.amazonaws.glue:aws-glue-datacatalog-client-common:jar:tests:1.10.0-SNAPSHOT, com.amazonaws.glue:aws-glue-datacatalog-spark-client:jar:tests:1.10.0-SNAPSHOT: Could not find artifact com.amazonaws.glue:aws-glue-datacatalog-client-common:jar:1.10.0-SNAPSHOT

**Comment by aws-austin-lee** [comment]
Your error message says that "com.amazonaws.glue:aws-glue-datacatalog-client-common:jar:1.10.0-SNAPSHOT" was not found.  Do you know why the aws-glue-datacatalog-client-common jar was not built?

**Comment by shreya668** [comment]
Yeah its is failing with:

**Comment by shreya668** [comment]
Yes it is failing with:

Failure to find com.amazonaws.glue:shims-loader:jar:1.10.0-SNAPSHOT. And the shims package is failing with exception:

Failed to execute goal on project shims-loader: Could not resolve dependencies for project com.amazonaws.glue:shims-loader:jar:1.10.0-SNAPSHOT: Failure to find com.amazonaws.glue:spark-hive-shims:jar:1.10.0-SNAPSHOT

**Comment by aws-austin-lee** [comment]
I suspect that you are not pointing to the right version of Hive in your local repo.  For the HIve2 client, you need Hive 2.x and for the Spark client, you need Hive 1.2.  The error message you posted indicates you are pointing to Hive 1.2.3 to build the Hive2 client.

**Comment by shreya668** [comment]
I have set:
<hive2.version>2.3.4-SNAPSHOT</hive2.version>
<spark-hive.version>1.2.3-SNAPSHOT</spark-hive.version>

in pom.xml. spark-hive-shims is failing with "The following artifacts could not be resolved: org.spark-project.hive:hive-exec:jar:1.2.3-SNAPSHOT, org.spark-project.hive:hive-metastore:jar:1.2.3-SNAPSHOT". So not sure. Did build the hive branch1.2 also.

**Comment by aws-austin-lee** [comment]
Did you build Hive and Spark locally and did you do "mvn install"?

**Comment by shreya668** [comment]
Yes, Hive (1.2 and 2.3) have built locally. Did not build spark as was just trying to compile Hive glue client.
Should i build spark also locally ?

**Comment by aws-austin-lee** [comment]
No, you don't need to build the Spark client.  Can you just cd into the Hiv2 client directory and run "mvn clean package" from there?  That way, you're only building the Hive2 client.  Can you confirm that you installed Hive locally with the version "2.3.4-SNAPSHOT" which should be the version in pom.xml of the Hive root directory.

**Comment by shreya668** [comment]
Yes tried that. its able to find the dependencies for Hive 2.3.4-SNAPSHOT, so it is installed locally. It fails while resolving the artifact com.amazonaws.glue:aws-glue-datacatalog-client-common:jar:1.10.0-SNAPSHOT.

And when I try building aws-glue-datacatalog-client-common, it fails with "unable to  find com.amazonaws.glue:shims-loader:jar:1.10.0-SNAPSHOT".

**Comment by aws-austin-lee** [comment]
So, there must have been an error that tells you why the glue shim loader failed to build?

**Comment by aws-austin-lee** [comment]
@shreya668 any luck?  Please let us know if you need any further assistance.

**Comment by shreya668** [comment]
@aws-austin-lee : Yes, did few packaging changes and was able to compile it.
Thanks for your time.

**Comment by aws-austin-lee** [comment]
Thanks for confirming.  Let us know if any of the steps in the instructions were not clear enough.  Resolving this issue.

**Comment by khush-bhatia** [comment]
What was the resolution ? I am running into the same issue.  I have built 1.2.3-SNAPSHOT and set 
`<spark-hive.version>1.2.3-SNAPSHOT</spark-hive.version>`
in pom.xml

**Comment by BVemployee** [comment]
Running into this as well.  I have built and set hive 2.3.7-SNAPSHOT and 1.2.3-SNAPSHOT with the appropriate patches. 
```xml
    <hive2.version>2.3.7-SNAPSHOT</hive2.version>
    <spark-hive.version>1.2.3-SNAPSHOT</spark-hive.version>
```

**Comment by BVemployee** [comment]
If anyone else comes across this before the PR is merged my issue is resolved with #14

**Comment by SamanSattari** [comment]
I am running to the same issue. Following on what @BVemployee mentioned. I copied all packages to `~/.m2/repository/org/spark-project/hive/`. But now I get another error: 
```
[ERROR] /Users/samansattari/projects/Sanoma/aws-glue-data-catalog-client-for-apache-hive-metastore/shims/spark-hive-shims/src/main/java/com/amazonaws/glue/shims/AwsGlueSparkHiveShims.java:[3,29] error: package org.apache.hadoop.conf does not exist
[ERROR]
[ERROR] /Users/samansattari/projects/Sanoma/aws-glue-data-catalog-client-for-apache-hive-metastore/shims/spark-hive-shims/src/main/java/com/amazonaws/glue/shims/AwsGlueSparkHiveShims.java:[4,27] error: cannot find symbol
[ERROR]
[ERROR]  package org.apache.hadoop.fs
[ERROR] /Users/samansattari/projects/Sanoma/aws-glue-data-catalog-client-for-apache-hive-metastore/shims/spark-hive-shims/src/main/java/com/amazonaws/glue/shims/AwsGlueSparkHiveShims.java:[34,9] error: cannot find symbol
[ERROR]
[ERROR]  class AwsGlueSparkHiveShims
[ERROR] /Users/samansattari/projects/Sanoma/aws-glue-data-catalog-client-for-apache-hive-metastore/shims/spark-hive-shims/src/main/java/com/amazonaws/glue/shims/AwsGlueSparkHiveShims.java:[39,48] error: cannot find symbol
[ERROR]
[ERROR]  class AwsGlueSparkHiveShims
[ERROR] /Users/samansattari/projects/Sanoma/aws-glue-data-catalog-client-for-apache-hive-metastore/shims/spark-hive-shims/src/main/java/com/amazonaws/glue/shims/AwsGlueSparkHiveShims.java:[45,6] error: cannot find symbol
```
I am using 
```
<hive2.version>2.3.7-SNAPSHOT</hive2.version>
<spark-hive.version>1.2.3-SNAPSHOT</spark-hive.version>
```

**Comment by itamar-otonomo** [comment]
Anyone experienced a successful build lately and cares to share their experience?
This one is a real bugger!
Thanks!

**Comment by itamar-otonomo** [comment]
> @aws-austin-lee : Yes, did few packaging changes and was able to compile it.
> Thanks for your time.

Hi @shreya668,
I'm stuck with the same issue, can you describe the solution please?
This is so frustrating!
Thanks!

**Comment by jiajie999** [comment]
> > @aws-austin-lee : Yes, did few packaging changes and was able to compile it.
> > Thanks for your time.
> 
> Hi @shreya668,
> I'm stuck with the same issue, can you describe the solution please?
> This is so frustrating!
> Thanks!

Same problem

**Comment by vivek-menon** [comment]
The steps mentioned here - https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/issues/21 atleast resolves some of the issue but I am still unable to built it completely.
